name: Build Signed Fdroid APKs Directly

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g" -Dkotlin.daemon.jvm.options="-Xmx2560m"
  CI_GRADLE_ARG_PROPERTIES: --stacktrace --max-workers 2 --no-daemon

jobs:
  build-signed-fdroid:
    name: Build signed Fdroid APKs for all ABIs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Write signing key from secret
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 --decode > release.keystore

      - name: Set up signing config
        run: |
          cat <<EOF >> local.properties
          MYAPP_RELEASE_STORE_FILE=\$PWD/release.keystore
          MYAPP_RELEASE_KEY_ALIAS=${{ secrets.SIGNING_ALIAS }}
          MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.SIGNING_STOREPASS }}
          MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.SIGNING_KEYPASS }}
          EOF

      - name: Clean and build signed Fdroid APKs for all ABIs
        run: |
          ./gradlew clean assembleFdroidRelease $CI_GRADLE_ARG_PROPERTIES

      - name: Upload signed APKs for all ABIs
        uses: actions/upload-artifact@v4
        with:
          name: vector-fdroid-release-all
          path: |
            vector-app/build/outputs/apk/fdroid/release/*.apk
