name: Build Signed Fdroid APKs Directly

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g" -Dkotlin.daemon.jvm.options="-Xmx2560m"
  CI_GRADLE_ARG_PROPERTIES: --stacktrace --max-workers 2 --no-daemon

jobs:
  build-signed-fdroid:
    name: Build signed Fdroid APKs for all ABIs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Clean and build unsigned Fdroid APKs for all ABIs
        run: |
          ./gradlew clean assembleFdroidRelease $CI_GRADLE_ARG_PROPERTIES

      # 使用 ilharp/sign-android-release@v2 进行签名
      - uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: vector-app/build/outputs/apk/fdroid/release
          signingKey: ${{ secrets.SIGNING_KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STOREPASS }}
          keyPassword: ${{ secrets.SIGNING_KEYPASS }}
          buildToolsVersion: 36.0.0

      # 分割签名后的文件
      - uses: jungwinter/split@v2
        id: signed_files
        with:
          msg: ${{ steps.sign_app.outputs.signedFiles }}
          separator: ':'

      # 自动创建发布并上传签名后的APK
      - name: Example Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release X"
          files: |
            ${{ steps.signed_files.outputs._0 }}
            ${{ steps.signed_files.outputs._1 }}
            ${{ steps.signed_files.outputs._2 }}
            ${{ steps.signed_files.outputs._3 }}
            ${{ steps.signed_files.outputs._4 }}
